#!/usr/bin/env node

const utils = require("./bin/tools/utils");
const fs = require("fs");

(async function() {
  console.log("pwd=" + process.cwd());
  let files = await fs.promises.readdir(".");
  console.log("files=\n  " + files.join("\n  "));
  await utils.bootstrapCompiler(require("./package.json"));
  
  process.exit(0);
  
})();

