#!/usr/bin/env node

const utils = require("./bin/tools/utils");
const fs = require("fs");

(async function() {
  let version = process.argv[2];  
  if (!version) {
     version = require("./package.json").version;
  }
  let upgradeFramework = false;
  if (process.argv.length > 2) {
    if (process.argv[2] == "--upgrade-framework") {
      upgradeFramework = true;
    }
  }
  await utils.bootstrapCompiler(version, upgradeFramework);
  process.exit(0);
})();



